# Generated by Django 3.0.9 on 2021-04-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210414_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='labour_p',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat_p',
            field=models.FloatField(default=16.5),
        ),
    ]
