# Generated by Django 3.0.9 on 2021-06-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210425_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='labour_p',
            field=models.FloatField(default=30.0),
        ),
    ]
